enum MetricAggregation { sum, ratio, maximum, minimum }

class StatisticsMetric {
  const StatisticsMetric(
    this.id,
    this.title,
    this.category,
    this.explanation, {
    this.denominator,
    this.factor = 1,
    this.unit = '',
    this.aggregation = MetricAggregation.sum,
    this.lowerIsBetter = false,
  });
  final String id, title, category, explanation, unit;
  final String? denominator;
  final double factor;
  final MetricAggregation aggregation;
  final bool lowerIsBetter;
  String format(double? value) => value == null
      ? '—'
      : '${value.toStringAsFixed(aggregation == MetricAggregation.ratio ? 2 : 0)}${unit.isEmpty ? '' : ' $unit'}';
}

const statisticsMetrics = <StatisticsMetric>[
  StatisticsMetric(
    'matches',
    'Spiele',
    'Ergebnisse',
    'Abgeschlossene Spiele. Laufende Scorer-Sitzungen zählen nur zu den Aufnahme-Statistiken.',
  ),
  StatisticsMetric(
    'wins',
    'Siege',
    'Ergebnisse',
    'Gewonnene abgeschlossene Spiele.',
  ),
  StatisticsMetric(
    'losses',
    'Niederlagen',
    'Ergebnisse',
    'Verlorene abgeschlossene Spiele.',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'draws',
    'Unentschieden',
    'Ergebnisse',
    'Abgeschlossene Spiele mit gleichem Ergebnis.',
  ),
  StatisticsMetric(
    'wins',
    'Siegquote',
    'Ergebnisse',
    'Siege geteilt durch alle abgeschlossenen Spiele. Unentschieden zählen als Spiel, aber nicht als Sieg.',
    denominator: 'matches',
    factor: 100,
    unit: '%',
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'legsWon',
    'Gewonnene Legs',
    'Legs & Sets',
    'Gewonnene Legs aus Ergebnissen oder abgeschlossenen Scorer-Legs.',
  ),
  StatisticsMetric(
    'legsLost',
    'Verlorene Legs',
    'Legs & Sets',
    'Verlorene Legs aus Ergebnissen oder abgeschlossenen Scorer-Legs.',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'legsWon',
    'Legquote',
    'Legs & Sets',
    'Gewonnene Legs geteilt durch alle abgeschlossenen Legs.',
    denominator: 'legs',
    factor: 100,
    unit: '%',
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'setsWon',
    'Gewonnene Sets',
    'Legs & Sets',
    'Erfasste Set-Ergebnisse; Spiele ohne Set-Ergebnis liefern keinen Wert.',
  ),
  StatisticsMetric(
    'setsLost',
    'Verlorene Sets',
    'Legs & Sets',
    'Erfasste verlorene Sets.',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'points',
    '3-Dart-Average',
    'Scoring',
    'Dreifache Summe der erzielten Punkte geteilt durch die tatsächlich gezählten Darts. Kein Mittelwert der Spiel-Averages.',
    denominator: 'darts',
    factor: 3,
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'firstPoints',
    'First-9-Average',
    'Scoring',
    'Die ersten drei Aufnahmen je Leg, gewichtet nach gezählten Darts.',
    denominator: 'firstDarts',
    factor: 3,
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'points',
    'Erzielte Punkte',
    'Scoring',
    'Summe der gewerteten Punkte aus Scorer-Aufnahmen.',
  ),
  StatisticsMetric(
    'thrownDarts',
    'Geworfene Pfeile',
    'Scoring',
    'Alle erfassten Würfe, einschließlich Fehlwürfen, tatsächlichen Überwurf-Darts und noch offenen Aufnahmen. Keine Trefferposition erforderlich. Bei manuellen Punktesummen und alten Spielen wird die gespeicherte Dartanzahl verwendet; diese Anteile sind unter „Geschätzte Wurfanzahl“ ausgewiesen. Rückgängig gemachte Würfe zählen nicht.',
  ),
  StatisticsMetric(
    'estimatedThrownDarts',
    'Geschätzte Wurfanzahl',
    'Scoring',
    'Anteil der geworfenen Pfeile aus manuellen Punktesummen oder alten Aufnahmen ohne einzeln erfasste Dartanzahl. Bei regulären manuellen Aufnahmen werden drei Darts angenommen.',
  ),
  StatisticsMetric(
    'darts',
    'Für Average gezählte Darts',
    'Scoring',
    'Darts für die Average-Berechnung. Nicht abgeschlossene Aufnahmen fehlen; Überwürfe zählen regelgemäß als drei Darts, auch wenn weniger Pfeile geworfen wurden.',
  ),
  StatisticsMetric(
    'visits',
    'Aufnahmen',
    'Scoring',
    'Anzahl erfasster Aufnahmen.',
  ),
  StatisticsMetric(
    'scores60',
    '60+ Aufnahmen',
    'Scoring',
    'Aufnahmen mit mindestens 60 Punkten, einschließlich 100+, 140+ und 180.',
  ),
  StatisticsMetric(
    'scores100',
    '100+ Aufnahmen',
    'Scoring',
    'Aufnahmen mit mindestens 100 Punkten, einschließlich 140+ und 180.',
  ),
  StatisticsMetric(
    'scores140',
    '140+ Aufnahmen',
    'Scoring',
    'Aufnahmen mit mindestens 140 Punkten, einschließlich 180.',
  ),
  StatisticsMetric(
    'scores180',
    '180er',
    'Scoring',
    'Aufnahmen mit genau 180 Punkten.',
  ),
  StatisticsMetric(
    'scores180',
    '180er je 100 Aufnahmen',
    'Scoring',
    '180er geteilt durch alle erfassten Aufnahmen, mal 100.',
    denominator: 'visits',
    factor: 100,
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'highestScore',
    'Höchste Aufnahme',
    'Scoring',
    'Höchster erfasster Aufnahmewert.',
    aggregation: MetricAggregation.maximum,
  ),
  StatisticsMetric(
    'busts',
    'Überwürfe',
    'Scoring',
    'Erfasste Aufnahmen, die als Überwurf gewertet wurden.',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'busts',
    'Überwurfquote',
    'Scoring',
    'Überwürfe geteilt durch alle Aufnahmen.',
    denominator: 'visits',
    factor: 100,
    unit: '%',
    aggregation: MetricAggregation.ratio,
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'finishes',
    'Checkoutquote',
    'Checkout',
    'Gewonnene Double-Out-Legs geteilt durch erfasste Checkoutversuche. Bei unbekannten Versuchen wird keine Quote berechnet.',
    denominator: 'attempts',
    factor: 100,
    unit: '%',
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'attempts',
    'Checkoutversuche',
    'Checkout',
    'Bekannte Checkoutversuche in Double-Out-Spielen. Nicht erfasste Versuche werden gesondert angezeigt.',
  ),
  StatisticsMetric(
    'finishes',
    'Erfolgreiche Checkouts',
    'Checkout',
    'Erfasste gewonnene Double-Out-Legs.',
  ),
  StatisticsMetric(
    'highestFinish',
    'Höchstes Finish',
    'Checkout',
    'Höchster erfasster Finishwert.',
    aggregation: MetricAggregation.maximum,
  ),
  StatisticsMetric(
    'tonFinishes',
    '100+ Finishes',
    'Checkout',
    'Erfasste Finishes mit mindestens 100 Punkten.',
  ),
  StatisticsMetric(
    'unknownAttempts',
    'Unbekannte Checkout-Aufnahmen',
    'Checkout',
    'Double-Out-Aufnahmen ohne erfasste Checkoutversuche. Diese Lücken verhindern eine verlässliche Gesamtquote.',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'bestLeg',
    'Bestes Leg',
    'Legqualität',
    'Geringste Dartzahl eines gewonnenen Legs. Unterschiedliche Startpunktzahlen beachten.',
    aggregation: MetricAggregation.minimum,
    unit: 'Darts',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'wonLegDarts',
    'Darts je gewonnenem Leg',
    'Legqualität',
    'Gezählte Darts in gewonnenen Legs geteilt durch die Anzahl dieser Legs.',
    denominator: 'scorerLegsWon',
    aggregation: MetricAggregation.ratio,
    unit: 'Darts',
    lowerIsBetter: true,
  ),
  StatisticsMetric(
    'breaks',
    'Breaks',
    'Legqualität',
    'Gewonnene Legs bei gegnerischem Anwurf in Spielen mit zwei Teilnehmern.',
  ),
  StatisticsMetric(
    'holds',
    'Holds',
    'Legqualität',
    'Gewonnene Legs bei eigenem Anwurf in Spielen mit zwei Teilnehmern.',
  ),
  StatisticsMetric(
    'shortLegs',
    'Shortlegs bis 18 Darts',
    'Legqualität',
    'Gewonnene Legs mit höchstens 18 Darts, unabhängig von Startpunktzahl.',
  ),
  StatisticsMetric(
    'nineDarters',
    '9-Darter',
    'Legqualität',
    'Gewonnene 501-Legs mit genau neun Darts unter Standardregeln.',
  ),
  StatisticsMetric(
    'sessions',
    'Erfasste Sitzungen / Begegnungen',
    'Aktivität & Datenbasis',
    'Alle berücksichtigten Sitzungen beziehungsweise Spielerbegegnungen. In Doppelspielen zählt jeder Spielerbeitrag separat.',
  ),
  StatisticsMetric(
    'scorerGames',
    'Spiele mit Scorer-Daten',
    'Aktivität & Datenbasis',
    'Begegnungen mit mindestens einer erfassten Aufnahme des Spielers.',
  ),
  StatisticsMetric(
    'incomplete',
    'Unvollständige Sitzungen',
    'Aktivität & Datenbasis',
    'Scorer-Sitzungen mit Aufnahmen, aber ohne abgeschlossenes Spielergebnis.',
  ),
  StatisticsMetric(
    'scorerGames',
    'Scorer-Datenabdeckung',
    'Aktivität & Datenbasis',
    'Spielerbegegnungen mit Scorer-Daten geteilt durch alle berücksichtigten Sitzungen und Begegnungen.',
    denominator: 'sessions',
    factor: 100,
    unit: '%',
    aggregation: MetricAggregation.ratio,
  ),
  StatisticsMetric(
    'doubleOutGames',
    'Double-Out-Sitzungen',
    'Aktivität & Datenbasis',
    'Scorer-Sitzungen mit aktivierter Double-Out-Regel. Ergebnisse ohne übertragene Aufnahmen liefern keine Regelangabe.',
  ),
];
