import 'dart:io';
import 'package:dart_tournament_manager/features/scorer/domain/x01/checkout_planner.dart';
import 'package:dart_tournament_manager/features/scorer/domain/x01/x01_models.dart';

// Offline generator only. The scorer reads the committed constant table.
void main() {
  final planner = CheckoutPlanner();
  final output = StringBuffer(
    '// Generated by tool/generate_scorer_checkouts.dart.\n'
    '// Schema v1: requirement / darts available / remaining score.\n'
    'const fixedCheckoutLabels = <String, List<List<String>>>{\n',
  );
  for (final requirement in CheckoutRequirement.values) {
    for (var darts = 1; darts <= 3; darts++) {
      for (var score = 1; score <= 180; score++) {
        final routes = planner.allCheckoutRoutes(
          score: score,
          dartsLeft: darts,
          checkoutRequirement: requirement,
        );
        final ranked =
            routes
                .map(
                  (route) => (
                    route: route,
                    rating: planner.scoreRoute(
                      route: route,
                      startScore: score,
                      totalDarts: darts,
                      checkoutRequirement: requirement,
                      playStyle: CheckoutPlayStyle.balanced,
                    ),
                  ),
                )
                .toList()
              ..sort((a, b) {
                final byScore = b.rating.compareTo(a.rating);
                return byScore != 0
                    ? byScore
                    : a.route
                          .map((d) => d.label)
                          .join(',')
                          .compareTo(b.route.map((d) => d.label).join(','));
              });
        if (ranked.isEmpty) continue;
        output.writeln("  '${requirement.name}/$darts/$score': [");
        for (final item in ranked.take(5)) {
          output.writeln(
            '    [${item.route.map((d) => "'${d.label}'").join(', ')}],',
          );
        }
        output.writeln('  ],');
      }
    }
  }
  output.writeln('};');
  File(
    'lib/features/scorer/data/fixed_checkout_labels.dart',
  ).writeAsStringSync(output.toString());
}
