// npm install --prefix build/rbac_sql_tests --no-audit --no-fund --ignore-scripts @electric-sql/pglite
// node tool/test_community_permissions.mjs
import { PGlite } from '../build/rbac_sql_tests/node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const owner='11111111-1111-1111-1111-111111111111';
const member='22222222-2222-2222-2222-222222222222';
const reader='33333333-3333-3333-3333-333333333333';
const group='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
await db.exec(`create role authenticated; create role anon; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to authenticated,anon;
grant execute on function auth.uid() to authenticated,anon;
alter default privileges in schema public grant all on tables to authenticated;`);
for (const path of ['supabase/schema.sql','supabase/migrations/202609210001_manual_community_members.sql',
 'supabase/migrations/202609220001_account_devices.sql','supabase/migrations/202609230001_community_devices.sql']) {
 await db.exec(await readFile(path,'utf8'));
}
await db.exec(`insert into auth.users values('${owner}'),('${member}'),('${reader}');
insert into public.player_profiles(id,user_id,display_name) values('${owner}','${owner}','Owner'),('${member}','${member}','Leader'),('${reader}','${reader}','Reader');
insert into public.communities(id,owner_user_id,name,invite_code) values('${group}','${owner}','Club','ABCD1234');
insert into public.community_members(community_id,user_id,role) values('${group}','${owner}','owner'),('${group}','${member}','member'),('${group}','${reader}','member');`);
await db.exec(await readFile('supabase/migrations/202610020001_community_permissions.sql','utf8'));
await db.exec(await readFile('supabase/migrations/202610020003_community_profile.sql','utf8'));
await db.exec(await readFile('supabase/migrations/202610020006_community_edit_permission.sql','utf8'));
await db.exec(await readFile('supabase/migrations/202610030001_community_ranking_setting.sql','utf8'));
await db.exec(await readFile('supabase/migrations/202610030002_community_rankings.sql','utf8'));
async function as(user) { await db.exec(`reset role; select set_config('request.jwt.claim.sub','${user}',false); set role authenticated;`); }
async function fails(sql,params=[]) { await assert.rejects(db.query(sql,params)); }
await as(reader);
await fails(`insert into public.community_rankings(community_id,name) values('${group}','Denied')`);
assert.equal((await db.query(`update public.communities set name='Unauthorized' where id='${group}' returning id`)).rows.length,0);
assert.deepEqual((await db.query(`select public.community_permissions('${group}') as p`)).rows[0].p,[]);
await fails(`select invite_code from public.communities where id='${group}'`);
await fails(`select public.community_invitation('${group}')`);
await fails(`select public.delete_community_tournament('${group}','absent')`);
await fails(`insert into public.community_roles(community_id,name,permissions) values('${group}','Hack',array['manage_roles'])`);
await as(owner);
await db.query(`update public.communities set name='Club Profile',description='Bio',avatar_base64='test' where id='${group}'`);
assert.equal((await db.query(`select avatar_base64 from public.communities where id='${group}'`)).rows[0].avatar_base64,'test');
assert.equal((await db.query(`select cardinality(public.community_permissions('${group}')) as n`)).rows[0].n,9);
const role=(await db.query(`insert into public.community_roles(community_id,name,permissions) values('${group}','Leitung',array['create_tournaments','lead_tournaments']) returning id`)).rows[0].id;
await db.query(`select public.assign_community_role($1,$2,$3)`,[group,member,role]);
await fails(`select public.remove_community_member('${group}','${owner}')`);
await as(member);
const payload={id:'rbac-test',name:'Test',communityId:group,players:[],stages:[],runStages:[],boardCount:1,activeStageIndex:0,completedStageIndexes:[]};
await db.query('select public.save_community_tournament($1)',[payload]);
await db.query('select public.save_community_tournament($1)',[{...payload,activeStageIndex:1}]);
await fails('select public.save_community_tournament($1)',[{...payload,name:'Changed'}]);
await fails('select public.save_community_tournament($1)',[{...payload,communityRankingIds:['training']}]);
await fails(`update public.tournaments set is_deleted=true where client_tournament_id='rbac-test'`);
await fails(`update public.tournaments set community_id=null where client_tournament_id='rbac-test'`);
await as(owner);
await db.query('select public.save_community_tournament($1)',[{...payload,name:'Owner edit',activeStageIndex:1}]);
assert.equal((await db.query(`select owner_user_id from public.tournaments where client_tournament_id='rbac-test'`)).rows[0].owner_user_id,member);
const limited=(await db.query(`insert into public.community_roles(community_id,name,permissions) values('${group}','Rollenhelfer',array['manage_roles']) returning id`)).rows[0].id;
await db.query('select public.assign_community_role($1,$2,$3)',[group,reader,limited]);
await as(reader);
await fails(`insert into public.community_roles(community_id,name,permissions) values('${group}','Escalate',array['manage_roles','delete_tournaments'])`);
await fails('select public.assign_community_role($1,$2,$3)',[group,reader,role]);
await fails('select public.assign_community_role($1,$2,$3)',[group,member,null]);
await as(owner);
await db.query('select public.assign_community_role($1,$2,$3)',[group,member,null]);
await as(member);
await fails('select public.save_community_tournament($1)',[{...payload,activeStageIndex:2}]);
await as(owner);
await db.query(`select public.remove_community_member($1,$2)`,[group,member]);
await db.query(`select public.delete_community_tournament($1,$2)`,[group,'absent-draft']);
await db.query(`select public.delete_community_tournament($1,$2)`,[group,'rbac-test']);
assert.equal((await db.query(`select is_deleted from public.tournaments where client_tournament_id='rbac-test'`)).rows[0].is_deleted,true);
await fails('select public.save_community_tournament($1)',[payload]);
await as(member);
assert.equal((await db.query(`select * from public.tournaments where client_tournament_id='rbac-test'`)).rows.length,0);
await as(reader);
await fails('select public.update_community_profile($1,$2,$3,$4)',[group,'Denied','Bio',null]);
await as(owner);
const editor = (await db.query(`insert into public.community_roles(community_id,name,permissions) values($1,'Profile editor',array['edit_community']) returning id`,[group])).rows[0].id;
await db.query('select public.assign_community_role($1,$2,$3)',[group,reader,editor]);
await as(reader);
const edited = (await db.query('select public.update_community_profile($1,$2,$3,$4) as profile',[group,'Edited','New bio','image'])).rows[0].profile;
await db.query(`insert into public.community_rankings(community_id,name) values($1,'Training'),($1,'Vereinsmeisterschaft')`,[group]);
assert.equal((await db.query('select * from public.community_rankings where community_id=$1',[group])).rows.length,2);
await fails(`insert into public.community_rankings(community_id,name) values($1,' training ')`,[group]);
await fails(`insert into public.community_rankings(community_id,name) values($1,'Standard-Rangliste')`,[group]);
await fails(`insert into public.community_rankings(community_id,name) values($1,' ')`,[group]);
assert.equal(edited.name,'Edited');
assert.equal((await db.query('select public.update_community_settings($1,$2,$3,$4,$5) as settings',[group,'Edited','Bio',null,false])).rows[0].settings.ranking_enabled,false);
assert.equal((await db.query('select public.update_community_settings($1,$2,$3,$4,$5) as settings',[group,'Edited','Bio',null,true])).rows[0].settings.ranking_enabled,true);
assert.equal(edited.owner_user_id,owner);
assert.equal('invite_code' in edited,false);
await fails('select public.update_community_profile($1,$2,$3,$4)',[group,'','Bio',null]);
assert.equal((await db.query(`update public.communities set owner_user_id=$1 where id=$2 returning id`,[reader,group])).rows.length,0);
await as(owner);
await db.query('select public.assign_community_role($1,$2,$3)',[group,reader,null]);
await as(reader);
await fails('select public.update_community_profile($1,$2,$3,$4)',[group,'Revoked','Bio',null]);
await fails('select public.update_community_settings($1,$2,$3,$4,$5)',[group,'Revoked','Bio',null,false]);
await fails(`insert into public.community_rankings(community_id,name) values($1,'Revoked')`,[group]);
assert.equal((await db.query('select * from public.community_rankings where community_id=$1',[group])).rows.length,2);
await as(member);
assert.equal((await db.query('select * from public.community_rankings where community_id=$1',[group])).rows.length,0);
console.log('PASS: nine rights, delegated profile editing, validation, revocation, ownership and invitation protection, existing role and tournament checks.');
await db.close();
