import {PGlite} from '../build/rbac_sql_tests/node_modules/@electric-sql/pglite/dist/index.js';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const owner='11111111-1111-1111-1111-111111111111', other='22222222-2222-2222-2222-222222222222';
const secret='a'.repeat(64), otherSecret='b'.repeat(64);
await db.exec(`create role authenticated;create role anon;create role service_role;
create schema auth;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to authenticated,anon,service_role;
create table public.player_profiles(user_id uuid,display_name text);
create table public.community_calendar_events(id uuid primary key,community_id uuid,title text,starts_at timestamptz,location text);
create table public.community_calendar_reminders(event_id uuid,user_id uuid,minutes_before integer);
create table public.community_members(community_id uuid,user_id uuid);
insert into auth.users values('${owner}'),('${other}');`);
await db.exec(await readFile('supabase/migrations/202610020003_app_push.sql','utf8'));
await db.exec(await readFile('supabase/migrations/202610030007_linux_notifications.sql','utf8'));
async function as(user) {await db.exec(`reset role;select set_config('request.jwt.claim.sub','${user}',false);set role authenticated;`);}
async function poll(key,ack=[],disable=false) {return (await db.query('select poll_linux_notifications($1,$2,$3) as data',[key,ack,disable])).rows[0].data;}
await as(owner);
const device=(await db.query('select register_linux_notification_device($1,$2) as id',[secret,'Linux'])).rows[0].id;
await as(other);
await assert.rejects(db.query('select register_linux_notification_device($1,$2)',[secret,'Hijack']));
const second=(await db.query('select register_linux_notification_device($1,$2) as id',[otherSecret,'Other'])).rows[0].id;
await db.exec('reset role');
await db.query(`insert into linux_notification_queue(device_id,dedupe_key,title,body) values($1,'one','Title','Body'),($2,'two','Private','Other')`,[device,second]);
await db.exec('set role anon');
await assert.rejects(db.query('select * from linux_notification_queue'));
await assert.rejects(poll('c'.repeat(64)));
const messages=await poll(secret); assert.equal(messages.length,1); assert.equal(messages[0].title,'Title');
assert.equal((await poll(secret,[messages[0].id])).length,0);
assert.equal((await poll(otherSecret)).length,1);
await db.exec(`reset role;
insert into community_calendar_events values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','Cup',now()+interval '5 minutes','Club');
insert into community_calendar_reminders values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','${owner}',15);
insert into community_members values('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','${owner}');set role anon;`);
const reminders=await poll(secret); assert.equal(reminders.length,1); assert.match(reminders[0].title,/Cup/);
assert.equal((await poll(secret,[reminders[0].id])).length,0);
assert.equal((await poll(secret)).length,0,'no duplicate reminder after ack');
await db.exec(`reset role;update community_calendar_events set starts_at=starts_at+interval '1 minute';set role anon;`);
assert.equal((await poll(secret)).length,1,'rescheduled reminder has distinct identity');
await db.exec('reset role;delete from community_members;set role anon;');
assert.equal((await poll(secret)).length,0,'membership loss suppresses queued reminder');
await poll(secret,[],true);
await assert.rejects(poll(secret));
assert.equal((await poll(otherSecret)).length,1,'revocation does not affect other devices');
await db.close();
console.log('PASS Linux notifications: RLS, scoped capabilities, account isolation, acknowledgments, calendar deduplication, rescheduling, membership checks and revocation.');
