import { PGlite } from '../build/rbac_sql_tests/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated;
create table communities(id uuid primary key);
create table community_rankings(id uuid primary key, community_id uuid);
create function is_community_member(uuid) returns boolean language sql as $$select current_setting('test.member')='yes'$$;
create function community_permissions(uuid) returns text[] language sql as $$select case when current_setting('test.manager')='yes' then array['manage_rankings'] else array[]::text[] end$$;
grant usage on schema public to authenticated;
grant select on community_rankings to authenticated;
insert into communities values('11111111-1111-4111-8111-111111111111');`);
await db.exec(readFileSync(new URL('../supabase/migrations/20261008180000_ranking_rules.sql',import.meta.url),'utf8'));
await db.exec(`set role authenticated; set test.member='yes'; set test.manager='no';`);
const insert=`insert into community_ranking_settings values('11111111-1111-4111-8111-111111111111','default',3,false)`;
await assert.rejects(db.exec(insert));
await db.exec(`set test.manager='yes';`);
await db.exec(insert);
await assert.rejects(db.exec(`update community_ranking_settings set validity_months=0`));
await db.exec(`update community_ranking_settings set deleted=true; set test.manager='no';`);
await db.exec(`update community_ranking_settings set deleted=false`);
assert.equal((await db.query('select deleted from community_ranking_settings')).rows[0].deleted,true);
await db.exec(`set test.member='no';`);
assert.equal((await db.query('select * from community_ranking_settings')).rows.length,0);
await db.close();
console.log('Ranking settings constraints and permissions: PASS');
