import { PGlite } from '../build/rbac_sql_tests/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create table auth.users(id uuid primary key);
create table player_profiles(id uuid primary key,display_name text);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table communities(id uuid primary key);
create table community_members(community_id uuid,user_id uuid,role text,unique(community_id,user_id));
create table community_guest_members(id uuid primary key default gen_random_uuid(),community_id uuid,display_name text);
create table tournaments(client_tournament_id text,community_id uuid,owner_user_id uuid,payload jsonb,is_deleted boolean default false);
create function can_lead_tournament(uuid,uuid,jsonb) returns boolean language sql as $$select auth.uid()=$2$$;
create function community_permissions(uuid) returns text[] language sql as $$select array['invite_members']$$;
grant usage on schema public,auth to authenticated,anon;`);
await db.exec(readFileSync(new URL('../supabase/migrations/20261008140000_tournament_invitations.sql',import.meta.url),'utf8'));
const owner='11111111-1111-4111-8111-111111111111', stranger='22222222-2222-4222-8222-222222222222', request='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${owner}'),('${stranger}'); set role authenticated; select set_config('request.jwt.claim.sub','${owner}',false);`);
const token=(await db.query(`select create_tournament_invitation('local','Test',null) as token`)).rows[0].token;
await db.exec(`set role anon; select set_config('request.jwt.claim.sub','',false);`);
assert.equal((await db.query('select tournament_invitation_info($1) as info',[token])).rows[0].info.title,'Test');
await db.query('select request_tournament_join($1,$2,$3)',[token,'Gast',request]);
await db.query('select request_tournament_join($1,$2,$3)',[token,'Gast',request]);
await assert.rejects(db.query('select * from tournament_join_requests'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${stranger}',false);`);
assert.equal((await db.query('select * from tournament_join_requests')).rows.length,0);
await assert.rejects(db.query('select resolve_tournament_join($1,true,$2,false)',[request,request]));
await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false);`);
assert.equal((await db.query('select * from tournament_join_requests')).rows.length,1);
await db.query('select resolve_tournament_join($1,true,$2,false)',[request,request]);
assert.equal((await db.query('select status from tournament_join_requests')).rows[0].status,'accepted');
await db.exec(`reset role; insert into player_profiles values('${stranger}','Account-Name'); set role authenticated; select set_config('request.jwt.claim.sub','${stranger}',false);`);
await db.query('select request_tournament_join($1,$2,$3)',[token,'Gefälschter Name','44444444-4444-4444-8444-444444444444']);
await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false);`);
assert.equal((await db.query('select display_name from tournament_join_requests where user_id=$1',[stranger])).rows[0].display_name,'Account-Name');
await db.close();
console.log('Tournament invitation SQL permissions and idempotency: PASS');
